### PR TITLE
SBOM from GHA

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
Migrated the old dockerfile approach of generating an SBOM, to the new gha version

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — DISMISSED** [review]

**Comment by robbecker-wf** [comment]
QA+1 CI passes and the cyclone dx file is attached

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p :shipit:

**Comment by chrisgustavsen-wf** [comment]
@rmconsole-wf

**Comment by chrisgustavsen-wf** [comment]
re-check

**Comment by chrisgustavsen-wf** [comment]
@Workiva/release-management-p

**Comment by chrisgustavsen-wf** [comment]
Ok. Let it roll.

**Comment by chrisgustavsen-wf** [comment]
@Workiva/release-management-p

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Pull request closed without merging**
