### PR TITLE
FEA-3239: Updated scip Protobuf

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEA-3239](https://jira.atl.workiva.net/browse/FEA-3239)
Issue Status

The protobuf spec for scip has changed a good amount since the scip-dart indexer was originally written, this pr bumps, and regenerates protobuf assets from `0.2.3` to `0.3.3`

The main major code difference being the introduction of `signatureDocumentation`, an alternative to just re-using the `documentation` field on `SymbolInformation` to provide the display string of the symbol in question. One nice this about this change, is the reduction in snapshot bloat that the snapshot tests have (Closes #87)

One other addition is the concept of [`PositionEncoding`](https://github.com/sourcegraph/scip/blob/main/scip.proto#L121), this should also be populated, but I'm currently unsure what value it should be for the dart language in particular. This will be set as a followup in #115 

## QA
- [ ] Build and push some scip-dart index.scip files to a sourcegraph instance, and verify that symbols work as expected. Specifically look out for `signatureDocumentation`, verifying that signatures are populated in the sourcegraph popover

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by todbachman-wf — APPROVED** [review]

**Comment by matthewnitschke-wk** [comment]
QA +1

indexed and uploaded scip-dart to sourcegraph, verified that uploaded analysis is as you would expect

**Comment by matthewnitschke-wk** [comment]
🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
