### PR TITLE
FEA-3101: Added ast-printer dev tool

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEA-3101](https://jira.atl.workiva.net/browse/FEA-3101)
Issue Status

Sometimes it can be nice to visually see the ast tree when debugging parsing issues

This pr introduces an `ast_printer.dart` file which can be used to do just that

Here is an example running this tool on a small dart file
Screenshot 2023-12-20 at 2 51 36 PM

### CODE REVIEW

**Review by sorenthompson-wk — APPROVED** [review]
😎 cool

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x]  CI does indeed pass, changes are exclusively a internal dev tool

🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
