### PR TITLE
FEA-2796: Occurrence Diagnostics

### PR DESCRIPTION
**Pull request by matthewnitschke-wk**
# [FEA-2796](https://jira.atl.workiva.net/browse/FEA-2796)
Issue Status

Populates the `diagnostics` field on Occurrences: https://github.com/sourcegraph/scip/blob/main/scip.proto#L579 with data from the dart analyzer

Now that sourcegraph has fixed their gql provider for retrieving this diagnostic data: https://github.com/sourcegraph/sourcegraph/issues/56904, this data has become more helpful, and we should start populating it

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by evanweible-wf** [comment]
Should/could we update the snapshots to test the population of these diagnostics?

**Comment by matthewnitschke-wk** [comment]
@evanweible-wf 
> Should/could we update the snapshots to test the population of these diagnostics?

Unfortunately the snapshot command doesn't include diagnostics in what it writes

I considered writing my own (could even just be a json output thing), but its a bit more of a lift than I wanted to do for this PR

**Comment by evanweible-wf** [comment]
Nope that's fine with me - diagnostics are just extra, so as long as they don't break the generation in the first place, I'm fine not including them in the tests if it's a bigger lift

**Comment by matthewnitschke-wk** [comment]
> Nope that's fine with me - diagnostics are just extra, so as long as they don't break the generation in the first place, I'm fine not including them in the tests if it's a bigger lift

👍 The existing snapshot tests, and my integration tests should cover that breakage case: https://github.com/Workiva/scip-dart/actions/runs/6598256582/job/17926049013?pr=94

I would like to get some tests to cover that though, I'll create a ticket for it so I dont forget

**Comment by matthewnitschke-wk** [comment]
Ticketed https://github.com/Workiva/scip-dart/issues/98

**Comment by matthewnitschke-wk** [comment]
QA +1

- [x] CI passes, and diagnostic data is additional, doesn't effect existing scip data

🚀 @Workiva/release-management-p 🚢

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
